AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcCidr:
    Description: The CIDR block for the VPC
    Type: String
    Default: '10.0.0.0/21'
  MyIpParameter:
    Type: String
    Description: Your current public IP address
    NoEcho: true

Resources:
  OsakaGPTVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: OsakaGPTVPC

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref OsakaGPTVPC
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PublicSubnet

  NormalIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: NormalIGW

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref OsakaGPTVPC
      InternetGatewayId: !Ref NormalIGW

  NormalRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref OsakaGPTVPC
      Tags:
        - Key: Name
          Value: NormalRouteTable

  # LocalRoute:
  #   Type: 'AWS::EC2::Route'
  #   Properties:
  #     RouteTableId: !Ref NormalRouteTable
  #     DestinationCidrBlock: !Ref VpcCidr
  #     GatewayId: 'local'

  OutboundRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref NormalRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref NormalIGW

  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref NormalRouteTable

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: OsakaGPT security group
      VpcId: !Ref OsakaGPTVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  OsakaGPTNetworkAcl:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref OsakaGPTVPC

  NormalEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      # ImageId: ami-0d889f77081190db1
      # ImageId: ami-0d889f77081190db1
      ImageId: ami-0d94353f7bad10668
      InstanceType: t2.micro
      # InstanceType: p2.xlarge
      KeyName: virginiaKey
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref EC2SecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 20  # 20GB volume size
            VolumeType: "gp3"  # General Purpose SSD

  OsakaGPTEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref NormalEC2Instance
